.github/workflows/development.yml

update development.yml file

---

src/lib/components/transition/Spinner.svelte
src/pages/Auth/entry-point/EntryPoint.svelte
src/pages/Auth/forgot-password/ForgotPassword.svelte
src/pages/Auth/login-page/LoginPage.svelte
src/pages/Auth/reset-password/ResetPassword.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/update-password/update-password.ts

fix: auth bugs 

---

src/pages/Auth/update-password/UpdatePassword.svelte

Fix: resend verification code issue

Fix: resend verification code issue

---

src/pages/Auth/forgot-password/ForgotPassword.svelte
src/pages/Auth/update-password/UpdatePassword.svelte

fix refresh verification code
Fixes issue #482 of sparrow-app repository

fix: refresh verification code

---

src/App.svelte
src/lib/utils/dto/auth-dto.ts
src/pages/Auth/forgot-password/ForgotPassword.svelte
src/pages/Auth/reset-password/ResetPassword.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/update-password/update-password.ts

implement verification code auth at change password

Feat: implement verification code change password

---

src/pages/Auth/login-page/LoginPage.svelte
src/pages/Auth/register-page/RegisterPage.svelte
src/pages/Auth/reset-password/ResetPassword.svelte

This PR fixed the alignment of checkbox and the terms text in the register page [#1618] story.

fix: fixed ui alignment bug in 1618 [#1618]

---

src/pages/Auth/update-password/UpdatePassword.svelte

Fix: Fixed email text overlapping issue in Forgot Password page [#1921]

Fix: Fixed email text overlapping issue in Forgot Password page [#1921]

---

src/lib/utils/validation.ts

fixed user is able to add empty string in first name

fix: fixed user is able to add empty string in first name

---

src/lib/utils/validation.ts
src/pages/Auth/update-password/UpdatePassword.svelte

Development to Main PR for Sparrow New Release - Version 2.13.0

Release Version 2.13.0 [Merging development into prod]

---

src/App.svelte
src/pages/Auth/login-page/LoginPage.svelte
src/pages/Auth/password-login/PasswordLogin.ViewModel.ts
src/pages/Auth/password-login/PasswordLogin.svelte
src/pages/Auth/register-page/RegisterPage.svelte
src/pages/Auth/verify-email/VerifyEmail.svelte

In this PR i have revamped the whole login flow.

feat: revamped the login with password flow 

---

src/pages/Auth/cool-down-page/CoolDownPage.svelte
src/pages/Auth/register-page/RegisterPage.svelte

feat: sparrow edge button in auth 

---

src/App.svelte
src/pages/Auth/password-update-redirect/PasswordUpdateRedirect.svelte
src/pages/Auth/reset-password/ResetPassword.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte

In this PR i have added the redirect update password screen

fix: added update password screen

---

package.json
src/lib/utils/mixpanel/MixpanelEvent.ts
src/main.ts
src/pages/Auth/entry-point/EntryPoint.svelte
yarn.lock

feat: added mixpanel in auth repo []

---

src/pages/Auth/entry-point/EntryPoint.svelte

fixed grayed button text ,and its conditions where its grayed out

debugged-grayed-button

---

src/pages/Auth/cool-down-page/CoolDownPage.svelte

fixed difference from figma ui

ui-bug-cooldown page

---

src/lib/utils/validation.ts

sign up issues if user enters enter multiple spaces in first name
[#2358](https://github.com/sparrowapp-dev/sparrow-app/issues/2358)
1.Enter new email id in email field
2.Click on continue
3.Enter multiple spaces and then user first name
4.Fill up remaining information
5.Verify OTP
Bug 1-
Expected-
The user's first name should be present in the verification mail
Actual-
First name is not present as user provided spaces in first name
Bug 2
Expected-
team name should come properly after sign up
Actual-
Team name only contain '
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ETjqjEQw3PFOpVK8DPQ-oYoBAPmf8vRCY_NEbMUhzejUxw?e=8jr9WI
after solving the bug
https://techdome-my.sharepoint.com/:v:/g/personal/mahendra_singh_techdome_net_in/EannLDQWUSNKu9GGw6pRdq4BFFi …

sign up issues if user enters enter multiple spaces in first name #2358 

---

src/pages/Auth/oauth-redirect/OauthRedirect.svelte

Reverts sparrowapp-dev/sparrow-app-auth#126

Revert "One intermediate screen is present in dev after login, which is not present in figma (present in all the login and sign-up options) #2385"

---

src/pages/Auth/cool-down-page/CoolDownPage.svelte
src/pages/Auth/login-page/LoginPage.svelte
src/pages/Auth/oauth-redirect/OauthRedirect.svelte

Development to Main PR for Sparrow New Release - Version 2.17.1

Release Version 2.17.1 [Merging development into prod]

---

src/pages/Auth/forgot-password/ForgotPassword.svelte
src/pages/Auth/login-page/LoginPage.svelte
src/pages/Auth/oauth-redirect/OauthRedirect.svelte
src/pages/Auth/reset-password/ResetPassword.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/verify-email/VerifyEmail.svelte

One intermediate screen is present in dev after login, which is not present in figma (present in all the login and sign-up options)
[#2385](https://github.com/sparrowapp-dev/sparrow-app/issues/2385)

One intermediate screen is present in dev after login, which is not present in figma (present in all the login and sign-up options) #2385

---

src/pages/Auth/redirect/Redirect.svelte

Replaced the Hub text with previous text as the Hub functionality is on pending.

fix: reverted the hub text []

---

src/pages/Auth/entry-point/EntryPoint.svelte
src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte

1. change send magic code case
2. added ellipse in send magic code screen

solved login screen issue

---

src/pages/Auth/redirect/Redirect.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/update-password/update-password.ts
src/pages/Auth/verify-email/VerifyEmail.svelte
src/pages/Auth/verify-email/verify-email.ts
src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte

Fix the username in the redirect page.

Fix: Username in redirect page.

---

src/pages/Auth/redirect/Redirect.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/update-password/update-password.ts
src/pages/Auth/verify-email/VerifyEmail.svelte
src/pages/Auth/verify-email/verify-email.ts
src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte

Reverts sparrowapp-dev/sparrow-app-auth#145

Revert "Fix: Username in redirect page."

---

src/pages/Auth/entry-point/EntryPoint.svelte
src/pages/Auth/forgot-password/ForgotPassword.svelte
src/pages/Auth/login-page/LoginPage.svelte
src/pages/Auth/password-login/PasswordLogin.svelte
src/pages/Auth/register-page/RegisterPage.svelte
src/pages/Auth/update-password/UpdatePassword.svelte
src/pages/Auth/verify-email/VerifyEmail.svelte
src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte

Resolved UI bugs mentioned in the ticket SPRW-934

Fix: sign up flow bugs [SPRW-934]

---

.env.example

This PR updates the example env for better understanding.

docs: update .env.example file

---

src/pages/Auth/register-page/RegisterPage.svelte

In this pr, I have change the text for the trialflow in the register page.

Change text for trialflow in the register page

---

src/pages/Auth/entry-point/EntryPoint.svelte

Reverts sparrowapp-dev/sparrow-app-auth#205

Revert "feat: add selfhost redirection for desktop app"
